version: "3.3"

networks:
  web:
    external: true

services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    command:
      - "--log.level=DEBUG"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik.toml:/traefik.toml:ro"
      - "./config/traefik_dynamic.toml:/traefik_dynamic.toml:ro"
      - "./acme.json:/acme.json"
    networks:
      - "web"