[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$TTTTTTTTTTTEEEEEEESSSSSSTTTTTTT"
  ]

[http.routers.api]
  rule = "Host(`traefik.example.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
